# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

domain: tomohikonakamura.github.io
url: https://tomohikonakamura.github.io
baseurl: jaCappella_corpus

title: 'jaCappella Corpus'
description: 'jaCappella Corpus: Japanese a Cappella Vocal Ensemble Corpus'

theme: jekyll-theme-cayman

# Optional
google-analytics: G-9EPRVMYY0Z

# # For publication list
# scholar:
#   style: _data/ieee_based_custom.csl
#   allow_locale_overrides: false
#   sort_by: year,month
#   order: descending
#   source: _data
#   bibliography_template: bib
#   bibliography_list_tag: "ul"
