name: Build Jekyll site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: bundle install
        run: |
          bundle config set path 'vendor/bundle'
          bundle install
      - name: Build the site in the jekyll/builder container
        run: bundle exec jekyll build
      - name: App Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
